export const copy = {
  hook: ['Writing is hard.', 'Polishing shouldn\'t be.'],
  select: 'Select. Press ⌘⇧X.',
  refined: 'Refined in place.',
  slash: '/translate, /formal, /shorter — your commands.',
  models: 'DeepSeek or local Ollama.',
  name: 'typo',
  tagline: 'Instant AI text refinement.',
  url: 'typo.yuler.cc',
  repo: 'github.com/yuler/typo',
  spoken: 'Select any text, press one shortcut, and typo makes it better.',
  keys: ['⌘', '⇧', 'X'],
  mailTitle: 'New Message',
  mailTo: 'team@acme.com',
  mailSubject: 'Release update',
  greeting: 'Hi all,',
  draft: 'hey, i think we should of shiped this last week but the tests was failing alot',
  polished: 'Hi team, we should have shipped this last week, but the tests were failing frequently.',
  signature: '— Yu',
  commands: [
    { name: 'translate', input: 'Bonjour, on se voit demain !', output: 'Hello, see you tomorrow!' },
    { name: 'formal', input: 'can u send me the file asap', output: 'Could you please send me the file at your earliest convenience?' },
    { name: 'shorter', input: 'I just wanted to quickly follow up to see if you had a chance to look', output: 'Any update on this?' },
  ],
  providers: [
    { name: 'DeepSeek', note: 'Cloud API' },
    { name: 'Ollama', note: 'On your machine' },
  ],
}
