export const copy = {
  hook: ['写作很难。', '润色不该难。'],
  select: '选中文字，按下 ⌘⇧X。',
  refined: '原地替换，一步到位。',
  slash: '斜杠命令，随心定制。',
  models: '支持 DeepSeek，也支持本地 Ollama。',
  name: 'typo',
  tagline: '极速 AI 润色，任意应用可用。',
  url: 'typo.yuler.cc',
  repo: 'github.com/yuler/typo',
  spoken: '选中任意文字，按下快捷键，typo 帮你一键润色。',
  keys: ['⌘', '⇧', 'X'],
  mailTitle: '新邮件',
  mailToLabel: '收件人：',
  mailTo: 'team@acme.com',
  mailSubjectLabel: '主题：',
  mailSubject: '发布进度',
  greeting: '各位好，',
  draft: '那个，我觉得我们上周就因该发布了，但是测试一直再报错，所以拖到现在',
  polished: '我们原计划上周发布，但由于测试持续报错，进度推迟到了现在。',
  signature: '—— Yu',
  noteTitle: '备忘录',
  commands: [
    { name: 'translate', label: '翻译', input: '/translate 明天下午三点开会，别迟到。', output: 'Meeting at 3 PM tomorrow — please don\'t be late.' },
    { name: 'formal', label: '正式', input: '/formal 文件赶紧发我一下', output: '麻烦您方便时尽快将文件发送给我，谢谢。' },
    { name: 'shorter', label: '精简', input: '/shorter 我就是想简单跟进一下，看看你有没有时间看一下上次说的那个方案', output: '上次的方案看了吗？' },
  ],
  providers: [
    { name: 'DeepSeek', note: '云端 API' },
    { name: 'Ollama', note: '本地运行' },
  ],
}
