source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: ".ruby-version"

# Rails
gem "rails", github: "rails/rails", branch: "main"

# Rails solid database gems
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Drivers
gem "sqlite3", ">= 2.8"
# gem "trilogy", "~> 2.9"
# gem "pg", "~> 1.6"

# Assets
gem "propshaft"
gem "importmap-rails"
# gem "jsbundling-rails"
# gem "cssbundling-rails"

# Hotwire
gem "turbo-rails"
gem "stimulus-rails"

# Media handling
gem "image_processing", "~> 1.2"

# Features
# gem "commonmarker", "~> 2.6"

# Dashboard engines
gem "mission_control-jobs"

# API
# gem "jwt"
gem "jbuilder"
gem "ruby_llm"
gem "geared_pagination"


# HTTP Clients
# gem "faraday"
# gem "faraday-retry"
# gem "faraday-multipart"
# gem "faraday-follow_redirects"

# Payments
# gem "stripe"  # TODO: Implement Stripe integration when needed

# Others
# gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data"

# Deployment
gem "puma", ">= 5.0"
gem "bootsnap", require: false
# gem "kamal", require: false
# gem "thruster", require: false

group :development, :test do
  gem "dotenv-rails"
  # gem "dotenv"
  gem "debug"
  gem "letter_opener"
  gem "letter_opener_web"
  # gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
  # gem "hotwire-livereload"
  # gem "ruby-lsp-rails"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
