import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PKG_ROOT = resolve(__dirname, '..')
const LOCALES_DIR = join(PKG_ROOT, 'src', 'locales')
const OUTPUT_FILE = join(PKG_ROOT, 'src', 'generated', 'keys.d.ts')

const PLACEHOLDER = /\{(\w+)\}/g

interface Failure { file: string, message: string }

function loadJson(path: string): Record<string, string> {
  const text = readFileSync(path, 'utf8')
  return JSON.parse(text) as Record<string, string>
}

function listLocales(dir: string): string[] {
  try {
    return readdirSync(dir)
      .filter(f => f.endsWith('.json'))
      .map(f => f.replace(/\.json$/, ''))
      .sort()
  }
  catch {
    return []
  }
}

function placeholdersOf(value: string): Set<string> {
  const out = new Set<string>()
  let m: RegExpExecArray | null
  PLACEHOLDER.lastIndex = 0
  for (;;) {
    m = PLACEHOLDER.exec(value)
    if (m === null)
      break
    out.add(m[1]!)
  }
  return out
}

function verify(): { failures: Failure[], namespaces: Record<string, string[]> } {
  const failures: Failure[] = []
  const namespaces: Record<string, string[]> = {}

  function checkNamespace(ns: string, dir: string) {
    const locales = listLocales(dir)
    if (!locales.includes('en')) {
      failures.push({ file: dir, message: `Namespace "${ns}" is missing en.json` })
      return
    }

    const enPath = join(dir, 'en.json')
    const enMap = loadJson(enPath)
    const enKeys = Object.keys(enMap).sort()
    namespaces[ns] = enKeys

    for (const [k, v] of Object.entries(enMap)) {
      if (typeof v !== 'string' || v.length === 0) {
        failures.push({ file: enPath, message: `Empty value for "${k}" in namespace "${ns}"` })
      }
    }

    for (const locale of locales) {
      if (locale === 'en')
        continue
      const localePath = join(dir, `${locale}.json`)
      const localeMap = loadJson(localePath)
      const localeKeys = new Set(Object.keys(localeMap))

      for (const k of enKeys) {
        if (!localeKeys.has(k)) {
          failures.push({ file: localePath, message: `Missing key "${k}" in namespace "${ns}"` })
          continue
        }
        const v = localeMap[k]
        if (typeof v !== 'string' || v.length === 0) {
          failures.push({ file: localePath, message: `Empty value for "${k}" in namespace "${ns}"` })
          continue
        }
        const enPlaceholders = placeholdersOf(enMap[k]!)
        const localePlaceholders = placeholdersOf(v)
        for (const ph of enPlaceholders) {
          if (!localePlaceholders.has(ph)) {
            failures.push({
              file: localePath,
              message: `Value for "${k}" in namespace "${ns}" is missing placeholder {${ph}}`,
            })
          }
        }
        for (const ph of localePlaceholders) {
          if (!enPlaceholders.has(ph)) {
            failures.push({
              file: localePath,
              message: `Value for "${k}" in namespace "${ns}" has extra placeholder {${ph}} not in en.json`,
            })
          }
        }
      }

      for (const k of localeKeys) {
        if (!enKeys.includes(k)) {
          failures.push({
            file: localePath,
            message: `Extra key "${k}" in namespace "${ns}" not in en.json`,
          })
        }
      }
    }
  }

  // 1. Check root for 'common' namespace
  if (listLocales(LOCALES_DIR).includes('en')) {
    checkNamespace('common', LOCALES_DIR)
  }

  // 2. Check subdirectories for other namespaces
  const nsDirs = readdirSync(LOCALES_DIR, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name)
    .sort()

  for (const ns of nsDirs) {
    checkNamespace(ns, join(LOCALES_DIR, ns))
  }

  if (Object.keys(namespaces).length === 0) {
    failures.push({ file: LOCALES_DIR, message: `No translations found in ${LOCALES_DIR}` })
  }

  return { failures, namespaces }
}

function emitTypes(namespaces: Record<string, string[]>): string {
  const lines: string[] = [
    '// AUTO-GENERATED by packages/languages/scripts/generate-types.ts',
    '// Do not edit by hand. Run `pnpm --filter @typo/languages build` to regenerate.',
    '',
    'export interface MessageKeys {',
  ]
  for (const ns of Object.keys(namespaces).sort()) {
    const keys = namespaces[ns]!
    if (keys.length === 0) {
      lines.push(`  ${ns}: never`)
    }
    else {
      const union = keys.map(k => JSON.stringify(k)).join(' | ')
      lines.push(`  ${ns}: ${union}`)
    }
  }
  lines.push('}', '')
  lines.push('export type Namespace = keyof MessageKeys')
  lines.push('export type MessageKey<N extends Namespace = Namespace> = MessageKeys[N]')
  lines.push('')
  return lines.join('\n')
}

function main(): void {
  const isVerify = process.argv.includes('--verify')
  const { failures, namespaces } = verify()

  if (failures.length > 0) {
    for (const f of failures) {
      console.error(`✖ ${f.file}: ${f.message}`)
    }
    console.error(`\n${failures.length} translation problem(s) found.`)
    process.exit(1)
  }

  if (!isVerify) {
    const out = emitTypes(namespaces)
    writeFileSync(OUTPUT_FILE, out, 'utf8')
    console.log(`✓ Wrote ${OUTPUT_FILE} (${Object.keys(namespaces).length} namespaces).`)
  }
  else {
    console.log(`✓ All locales complete (${Object.keys(namespaces).length} namespaces).`)
  }
}

main()
