name: packages-ci

on:
  push:
    branches: [main]
    paths: &packages_paths
      - 'packages/**'
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - package.json
      - .github/workflows/packages-ci.yml
  pull_request:
    branches: [main]
    paths: *packages_paths

jobs:
  languages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test @typo/languages
        run: pnpm languages:build && pnpm languages:test
